### ISSUE TITLE
Error while starting connector (com.amazonaws.SdkClientException)

### ISSUE THREAD

**Issue by efthymiosh** [jcustenborder/kafka-connect-kinesis#3]
I'm trying to start the connector (v0.1.0.10) on a distributed kafka-connect cluster. I'm getting the following on the kafka connect logs:
```
[2017-11-28 13:20:56,730] INFO 172.26.104.54 - - [28/Nov/2017:13:20:56 +0000] "POST /connectors HTTP/1.1" 201 357  666 (org.apache.kafka.connect.runtime.rest.RestServer)
[2017-11-28 13:20:57,047] ERROR Error while starting connector KinesisSourceConnector (org.apache.kafka.connect.runtime.WorkerConnector)
com.amazonaws.SdkClientException: Unable to marshall request to JSON: Jackson jackson-core/jackson-dataformat-cbor incompatible library version detected.
You have two possible resolutions:
                1) Ensure the com.fasterxml.jackson.core:jackson-core & com.fasterxml.jackson.dataformat:jackson-dataformat-cbor libraries on your classpath have the same version number
                2) Disable CBOR wire-protocol by passing the -Dcom.amazonaws.sdk.disableCbor property or setting the AWS_CBOR_DISABLE environment variable (warning this may affect performance)
        at com.amazonaws.services.kinesis.model.transform.DescribeStreamRequestProtocolMarshaller.marshall(DescribeStreamRequestProtocolMarshaller.java:58)
        at com.amazonaws.services.kinesis.AmazonKinesisClient.executeDescribeStream(AmazonKinesisClient.java:711)
        at com.amazonaws.services.kinesis.AmazonKinesisClient.describeStream(AmazonKinesisClient.java:696)
        at com.github.jcustenborder.kafka.connect.kinesis.KinesisSourceConnector.start(KinesisSourceConnector.java:66)
        at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:100)
        at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:125)
        at org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:182)
        at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:210)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:872)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1300(DistributedHerder.java:100)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder$15.call(DistributedHerder.java:888)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder$15.call(DistributedHerder.java:884)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Jackson jackson-core/jackson-dataformat-cbor incompatible library version detected.
You have two possible resolutions:
                1) Ensure the com.fasterxml.jackson.core:jackson-core & com.fasterxml.jackson.dataformat:jackson-dataformat-cbor libraries on your classpath have the same version number
                2) Disable CBOR wire-protocol by passing the -Dcom.amazonaws.sdk.disableCbor property or setting the AWS_CBOR_DISABLE environment variable (warning this may affect performance)
        at com.amazonaws.protocol.json.SdkCborGenerator.getBytes(SdkCborGenerator.java:68)
        at com.amazonaws.protocol.json.internal.JsonProtocolMarshaller.finishMarshalling(JsonProtocolMarshaller.java:185)
        at com.amazonaws.protocol.json.internal.NullAsEmptyBodyProtocolRequestMarshaller.finishMarshalling(NullAsEmptyBodyProtocolRequestMarshaller.java:53)
        at com.amazonaws.services.kinesis.model.transform.DescribeStreamRequestProtocolMarshaller.marshall(DescribeStreamRequestProtocolMarshaller.java:56)
        ... 15 more
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.dataformat.cbor.CBORGenerator.getOutputContext()Lcom/fasterxml/jackson/core/json/JsonWriteContext;
        at com.fasterxml.jackson.dataformat.cbor.CBORGenerator.close(CBORGenerator.java:903)
        at com.amazonaws.protocol.json.SdkJsonGenerator.close(SdkJsonGenerator.java:253)
        at com.amazonaws.protocol.json.SdkJsonGenerator.getBytes(SdkJsonGenerator.java:268)
        at com.amazonaws.protocol.json.SdkCborGenerator.getBytes(SdkCborGenerator.java:66)
        ... 18 more
[2017-11-28 13:20:57,061] INFO Finished creating connector KinesisSourceConnector (org.apache.kafka.connect.runtime.Worker)
```

The connector seems to start fine if the AWS_CBOR_DISABLE env var is set.

**Comment by jcustenborder** [comment]
@efthymiosh Thanks for the bug report. They use an old version of jackson. I went ahead and disabled CBOR when the task starts. This should resolve the problem. I'll release a fix very shortly.
