### ISSUE TITLE
com.github.jcustenborder.kafka.connect.utils.VersionUtil doesn't exist

### ISSUE THREAD

**Issue by reedbj** [jcustenborder/kafka-connect-kinesis#5]
Am I missing something, or are you missing a utils folder and associated code?

[2018-03-21 14:58:37,678] INFO Loading plugin from: /usr/share/java/kafka-2-kinesis (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
Exception in thread "main" java.lang.NoClassDefFoundError: com/github/jcustenborder/kafka/connect/utils/VersionUtil
	at com.github.jcustenborder.kafka.connect.kinesis.KinesisSourceConnector.version(KinesisSourceConnector.java:53)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.getPluginDesc(DelegatingClassLoader.java:279)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanPluginPath(DelegatingClassLoader.java:260)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanUrlsAndAddPlugins(DelegatingClassLoader.java:201)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.registerPlugin(DelegatingClassLoader.java:193)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.initLoaders(DelegatingClassLoader.java:153)
	at org.apache.kafka.connect.runtime.isolation.Plugins.<init>(Plugins.java:47)
	at org.apache.kafka.connect.cli.ConnectDistributed.main(ConnectDistributed.java:70)
Caused by: java.lang.ClassNotFoundException: com.github.jcustenborder.kafka.connect.utils.VersionUtil
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:62)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more

**Comment by reedbj** [comment]
I was just looking at the source and failed to notice that maven was set up to pull the code in.  my mistake!
